### PR TITLE
Feat: Upgrade to storybook 8

### PR DESCRIPTION
**Pull request by rustybud**
This pull request upgrades the addon to Storybook 8 and contains the following improvements:

- Renamed some types for clarity.
- Refactored some code inside Panel tsx.

Please review the changes and provide feedback. Thank you

### CODE REVIEW

**Comment by rustybud** [comment]
This PR should Update to storybook 8. I made sure build scripts are working correctly. There are no pipelines though to make sure this PR works. Waiting for feedback, Thank you.

**Review by krzysztofradomski — CHANGES_REQUESTED** [review]
I've made a pull request against your branch with the changes required to properly run this locally. So a lot of changes required to fully setting up Storybook 8, and also cleaned up scripts.

**Comment by rustybud** [comment]
I completely missed the components side of and I only upgraded the addon code.
Thank you so much for the PR, I just merged it 😊

**Comment by krzysztofradomski** [comment]
> I completely missed the components side of and I only upgraded the addon code. Thank you so much for the PR, I just merged it 😊

Thanks, I will try to have a look later today.

**Comment by rustybud** [comment]
Sure, I will work on it today.

**Comment by krzysztofradomski** [comment]
> Sure, I will work on it today.

How is it going? :)

**Pull request merged**
